"use strict";
let car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car == 'toyota'? I predict False.");
console.log(car == 'toyota');
console.log("Is car === 'Subaru'? I predict False.");
console.log(car === 'Subaru');
console.log("Is car != 'ford'? I predict True.");
console.log(car != 'ford');
console.log("Is car !== 'Subaru'? I predict True.");
console.log(car !== 'Subaru');
console.log("Is car.length > 5? I predict False.");
console.log(car.length > 5);
console.log("Is car.length < 10? I predict True.");
console.log(car.length < 10);
console.log("Does car start with 'su'? I predict True.");
console.log(car.startsWith('su'));
console.log("Does car end with 'ru'? I predict True.");
console.log(car.endsWith('ru'));
console.log("Does car include 'bar'? I predict False.");
console.log(car.includes('bar'));
